services:
  backend:
    build: ./backend
    image: weather-app-backend
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    image: weather-app-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
