apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: weather-backend
  template:
    metadata:
      labels:
        app: weather-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        envFrom: {{- toYaml .Values.backend.envFrom | nindent 12 }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        resources: {{- toYaml .Values.backend.resources | nindent 10 }}
