apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: weather-backend
  template:
    metadata:
      labels:
        app: weather-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom: {{- toYaml .Values.backend.envFrom | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 5
          resources: {{- toYaml .Values.backend.resources | nindent 12 }}
