grafana:
  enabled: true
  adminPassword: admin123
  service:
    type: LoadBalancer
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: false