replicaCount: 1

backend:
  image: ngeek4geek/weather-app-backend:latest
  port: 5000
  envFrom:
    - secretRef:
        name: weather-secret
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

frontend:
  image: ngeek4geek/weather-app-frontend:latest
  port: 80
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"

ingress:
  enabled: false
  host: weather.local