replicaCount: 1

backend:
  image: ngeek4geek/weather-app-backend:latest
  port: 5000
  envFrom:
    - secretRef:
        name: weather-secret
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  service:
    type: LoadBalancer
    port: 5000
    externalTrafficPolicy: Cluster

frontend:
  image: ngeek4geek/weather-app-frontend:latest
  port: 80
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  service:
    type: LoadBalancer
    port: 80
    externalTrafficPolicy: Cluster

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: weather.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
