replicaCount: 1

backend:
  image: ngeek4geek/weather-app-backend:latest
  port: 5000
  envFrom:
    - secretRef:
        name: weather-secret
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  service:
    type: LoadBalancer
    port: 5000
    externalTrafficPolicy: Cluster

frontend:
  image: ngeek4geek/weather-app-frontend:latest
  port: 80
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  service:
    type: LoadBalancer
    port: 80
    externalTrafficPolicy: Cluster

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  hosts:
    - host: "*"
      paths:
        - path: /weather-app/
          pathType: Prefix
          backend:
            service:
              name: weather-frontend-svc
              port:
                number: 80
        - path: /weather-app/api/
          pathType: Prefix
          backend:
            service:
              name: weather-backend-svc
              port:
                number: 5000