replicaCount: 1

backend:
  image: ngeek4geek/weather-app-backend:latest
  port: 5000
  envFrom:
    - secretRef:
        name: weather-secret
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  service:
    type: LoadBalancer
    port: 5000
    externalTrafficPolicy: Cluster
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-04f2dc2e663bdb3d3,subnet-0bce2b9230c94a80c"

frontend:
  image: ngeek4geek/weather-app-frontend:latest
  port: 80
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  service:
    type: LoadBalancer
    port: 80
    externalTrafficPolicy: Cluster
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-04f2dc2e663bdb3d3,subnet-0bce2b9230c94a80c"

ingress:
  enabled: false
