name: Workflow for checking weather application

on:
    push:
        paths: 
          - 'backend/**'
          - '.github/workflows/frontend-ci.yml'
        branches: [ main ]
    pull_request:
        paths: 
          - 'backend/**'
          - '.github/workflows/frontend-ci.yml'
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout sourcode
          uses: actions/checkout@v3
        
        - name: Build docker image
          run: |
            cd backend
            docker build -t weather-app-backend .

        - name: Run docker container
          run: |
            docker rm -f weather-app-backend 2>/dev/null || true
            docker run -p 5000:5000 --name weather-app-backend weather-app-backend
            sleep 5
        
        - name: Check log if everything is good status
          run: docker logs -f weather-app-backend
        
        - name: Test application
          run: |
            sleep 10
            curl --fail http://localhost:5000/weather?city=London

        - name: Clean up
          if: always()
          run: |
            docker stop weather-app-backend
            docker rm weather-app-backend