name: backend workflow

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'helm/**'
      - '.github/workflows/backend*'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME:  ngeek4geek/weather-app-backend
          IMAGE_TAG: v1.${{ github.run_number }}
    
        steps:
        - name: Checkout sourcode
          uses: actions/checkout@v3
        
        - name: Setup docker buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to docker
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Build and push docker image
          uses: docker/build-push-action@v5
          with:
            context: ./backend
            push: true
            tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

        - name: Clean up
          if: always()
          run: |
            docker image prune -af
            docker builder prune -af
    deploy:
      needs: build
      runs-on: ubuntu-latest
      env:
        IMAGE_NAME: ngeek4geek/weather-app-backend
        IMAGE_TAG: v1.${{ github.run_number }}
        AWS_REGION: us-east-1
        AWS_CLUSTER: weather-app-cluster

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        run: |
          aws eks update-kubeconfig --name $AWS_CLUSTER --region $AWS_REGION

      - name: Get backend external URL
        id: get-ip
        run: |
          export URL=$(kubectl get svc weather-backend-svc -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "BACKEND_URL=http://$URL" >> $GITHUB_ENV
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Upgrade Helm Chart
        run: |
          helm upgrade weather ./helm \
          --install \
          --namespace default \
          --wait \
          --atomic \
          --timeout 20m \
          --set backend.image=$IMAGE_NAME:$IMAGE_TAG

      - name: Test backend calls backend correctly
        run: |
          curl --fail $BACKEND_URL:5000/weather?query=London