name: CD workflow

on:
  workflow_run:
    workflows: ["CI workflow"]   # <-- TÊN PHẢI ĐÚNG với name: trong ci.yml
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
        AWS_REGION: us-east-1
        CLUSTER_NAME: weather-app-cluster
        WEATHER_API: ${{ secrets.WEATHER_API }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
    
      - name: Setup weather api authentication
        run: |
          kubectl create secret generic weather-secret --from-literal=WEATHER_API=$WEATHER_API
          
      - name: Set up kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Helm upgrade --install
        run: |
          helm upgrade --install weather ./helm \
            --namespace default \
            --create-namespace \
            --wait \
            --timeout 180s

      - name: Port-forward & Test Backend
        run: |
          kubectl port-forward svc/weather-backend-svc 5100:5000 &
          sleep 5
          curl -s "http://localhost:5100/weather?query=Hanoi" | tee result.json

          if grep -q "temperature" result.json; then
            echo "Backend test passed"
          else
            echo "Backend test failed"
            exit 1
          fi

      - name: Port-forward & Test Frontend
        run: |
          kubectl port-forward svc/weather-frontend-svc 8180:80 &
          sleep 5
          curl -s http://localhost:8180 | grep -q "Weather App" && echo "Frontend test passed" || (echo "Frontend failed" && exit 1)
