name: CD workflow

on:
  workflow_run:
    workflows: ["CI workflow"]   # <-- TÊN PHẢI ĐÚNG với name: trong ci.yml
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy with Helm
        run: |
          helm upgrade --install weather ./helm --wait --timeout 180s

      - name: Port-forward & Test Backend
        run: |
          kubectl port-forward svc/weather-backend-svc 5000:5000 &
          sleep 5
          curl -s "http://localhost:5000/weather?query=Hanoi" | tee result.json

          if grep -q "temperature" result.json; then
            echo "Backend test passed"
          else
            echo "Backend test failed"
            exit 1
          fi

      - name: Port-forward & Test Frontend
        run: |
          kubectl port-forward svc/weather-frontend-svc 8080:80 &
          sleep 5
          curl -s http://localhost:8080 | grep -q "Weather App" && echo "Frontend test passed" || (echo "Frontend failed" && exit 1)
