name: Workflow for checking weather backend

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout sourcode
          uses: actions/checkout@v3

        - name: Create .env file from secret
          run: |
            echo "WEATHER_API=${{ secrets.WEATHER_API }}" > .env

        - name: Set up Docker
          uses: docker/setup-buildx-action@v3

        - name: Install Docker Compose
          run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose version

        - name: Build docker image
          run: |
            docker-compose up --build -d
            sleep 5
        
        - name: Test application
          run: |
            sleep 3
            curl --fail http://localhost:5000/weather?city=London
            curl --fail http://localhost:3000

        - name: Clean up
          if: always()
          run: |
            docker stop $(docker ps -q)