name: CI workflow

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout sourcode
          uses: actions/checkout@v3

        - name: Create .env file from secret
          run: |
            echo "WEATHER_API=${{ secrets.WEATHER_API }}" > .env
            echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env

        - name: Set up Docker
          uses: docker/setup-buildx-action@v3

        - name: Install Docker Compose
          run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose version

        - name: Clean up all image before create
          run: |
            if [ "$(docker ps -q)" ]; then
              docker stop $(docker ps -q)
              docker rm $(docker ps -aq)
            fi

        - name: Build docker image
          run: |
            docker-compose up --build -d
            sleep 5
        
        - name: Test application
          run: |
            sleep 3
            curl --fail http://localhost:5000/weather?city=London
            curl --fail http://localhost:3000
        
        - name: Login to docker hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Build and push frontend image
          uses: docker/build-push-action@v5
          with:
            context: ./frontend
            push: true
            tags: |
              ngeek4geek/weather-app-frontend:latest
              ngeek4geek/weather-app-frontend:${{ github.sha }}

        - name: Build and push backend image
          uses: docker/build-push-action@v5
          with:
            context: ./backend
            push: true
            tags: |
              ngeek4geek/weather-app-backend:latest
              ngeek4geek/weather-app-backend:${{ github.sha }}

        - name: Clean up
          if: always()
          run: |
            docker stop $(docker ps -q)