name: frontend workflow

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'helm/**'
      - '.github/workflow/frontend*'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME:  ngeek4geek/weather-app-frontend
          IMAGE_TAG: ${{ github.sha }}
    
        steps:
        - name: Checkout sourcode
          uses: actions/checkout@v3
        
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
        
        - name: Install dependecies and build
          working-directory: ./frontend
          run: |
            npm install
            npm run build
        
        - name: Setup docker buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to docker
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Build and push docker image
          uses: docker/build-push-action@v5
          with:
            context: ./frontend
            push: true
            tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

        - name: Clean up
          if: always()
          run: |
            docker image prune -af
            docker builder prune -af